import "@/styles/globals.css";
import type { Metadata } from "next";
import { ReduxProvider } from "./ReduxProvider";
import { poppins } from "@/assets/fonts";
import cx from "classnames";
import FlowbiteProvider from "@/components/Flowbite/FlowbiteProvider";
import { Toaster } from "react-hot-toast";
import "react-calendar/dist/Calendar.css";
import "@/styles/calendar.scss";
import "aos/dist/aos.css";
import 'react-circular-progressbar/dist/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html  lang="en">
      <body className={cx(poppins.className, poppins.variable)}>
        <ReduxProvider>
          <FlowbiteProvider>{children}</FlowbiteProvider>
          <Toaster position="top-right" />
        </ReduxProvider>
      </body>
    </html>
  );
}
